site_name: Dynamic System Simulator (DSS)
nav:
  - Overview: docs/overview.md
  - Installation: docs/installation.md
  - Streamlit GUI: docs/streamlit_gui.md
  - Models: docs/models.md
  - Core API: docs/core_api.md
  - Controllers & Wrappers: docs/controllers_wrappers.md
  - Scripts: docs/scripts.md
  - Extending: docs/extending.md
  - Troubleshooting: docs/troubleshooting.md
theme:
  name: readthedocs
markdown_extensions:
  - admonition
  - toc:
      permalink: true
